Vagrant.configure("2") do |config|
  config.vm.box = "debian12"

  names = ["backend", "frontend", "db"]
  ips = ["192.168.56.152", "192.168.56.151", "192.168.56.153"]

  names.each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ips[i]

      case name
      when "backend"
        node.vm.network "forwarded_port", guest: 30797, host: 30001
        node.vm.network "forwarded_port", guest: 8080, host: 8080
      when "frontend"
        node.vm.network "forwarded_port", guest: 30797, host: 30002
        node.vm.network "forwarded_port", guest: 8000, host: 8000
      when "db"
        node.vm.network "forwarded_port", guest: 5432, host: 30003
      end

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      node.vm.provision "file", source: "~/.ssh/vagrant_id_rsa.pub", destination: "/tmp/vagrant_id_rsa.pub"
      node.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y python3
        mkdir -p /home/vagrant/.ssh
        echo "$(cat /tmp/vagrant_id_rsa.pub)" > /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
        chmod 700 /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
