- name: Gerar e aplicar Secret Kubernetes com variáveis específicas para frontend
  hosts: vm-frontend
  become: true
  tasks:
    - name: Criar template do frontend-secret.yaml
      template:
        src: frontend-secret.yaml.j2
        dest: /home/vagrant/frontend-secret.yaml
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Aplicar Secret com kubectl
      shell: kubectl apply -f /home/vagrant/frontend-secret.yaml
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
