- name: Gerar e aplicar Secret Kubernetes com variáveis específicas por host
  hosts: backend  # ou frontend, conforme necessário
  become: true
  tasks:
    - name: Criar template do secret.yaml
      template:
        src: secret.yaml.j2
        dest: /home/vagrant/secret.yaml
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Aplicar Secret com kubectl
      shell: kubectl apply -f /home/vagrant/secret.yaml
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
