- name: Gerar e aplicar Secret Kubernetes com variáveis específicas para backend
  hosts: vm-backend
  become: true
  tasks:
    - name: Criar template do backend-secret.yaml
      template:
        src: backend-secret.yaml.j2
        dest: /home/vagrant/backend-secret.yaml
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Aplicar Secret com kubectl
      shell: kubectl apply -f /home/vagrant/backend-secret.yaml
      environment:
        KUBECONFIG: /home/vagrant/.kube/config