- name: Instalar e configurar PostgreSQL
  hosts: k8s_db
  become: yes
  vars:
    pg_user: devops
    pg_password: devops
    pg_database: devops_db

  tasks:
    - name: Instalar dependências do PostgreSQL para Ansible (psycopg2)
      become: yes
      apt:
        name: python3-psycopg2
        state: present
        update_cache: yes
    - name: Instalar PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Garantir que o serviço do PostgreSQL esteja iniciado
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Criar usuário do PostgreSQL
      become: true
      shell: |
        sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ pg_user }}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE USER {{ pg_user }} WITH PASSWORD '{{ pg_password }}' CREATEDB;"

    - name: Criar banco de dados
      become: true
      shell: |
        sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw {{ pg_database }} || \
        sudo -u postgres createdb -O {{ pg_user }} {{ pg_database }}

    - name: Adicionar variáveis de ambiente ao /etc/environment
      lineinfile:
        path: /etc/environment
        create: yes
        state: present
        line: "{{ item }}"
      loop:
        - "POSTGRES_USER={{ pg_user }}"
        - "POSTGRES_PASSWORD={{ pg_password }}"
        - "POSTGRES_DB={{ pg_database }}"

    - name: Exportar variáveis no .bashrc do usuário vagrant
      become: true
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
        insertafter: EOF
        state: present
      loop:
        - 'export POSTGRES_USER={{ pg_user }}'
        - 'export POSTGRES_PASSWORD={{ pg_password }}'
        - 'export POSTGRES_DB={{ pg_database }}'
