- name: Configurar clusters Kubernetes com kind
  import_playbook: setup_kind.yaml

- name: Instalar e configurar PostgreSQL
  import_playbook: install_postgres.yaml

- name: Instalar ArgoCD nos clusters frontend e backend
  import_playbook: install_argocd.yaml

- name: Configurar aplicação backend no ArgoCD
  import_playbook: configure_backend.yaml

- name: Configurar aplicação frontend no ArgoCD
  import_playbook: configure_frontend.yaml

- name: Aplicar secrets específicos para cada cluster
  import_playbook: apply_secret.yaml